### PR TITLE
attempted Windows fix

### PR DESCRIPTION
**Pull request by SimonBiggs**

### CODE REVIEW

**Comment by SimonBiggs** [comment]
This change here appears to have done the trick! :)

https://simonbiggs.visualstudio.com/layer_linter/_build/results?buildId=4

**Comment by SimonBiggs** [comment]
Well, there is still one test failure. But it appears to successfully run on Windows at least.

**Comment by seddonym** [comment]
Nice work! I think we're nearly there - that failing test has some forward slashes in it, if you were to apply a similar fix I think it might pass.

**Comment by seddonym** [comment]
Here are the offending tuples: https://github.com/seddonym/layer_linter/blob/master/tests/functional/dependencies/test_scanner.py#L22

**Comment by SimonBiggs** [comment]
Thanks @seddonym, here is the test results for that latest commit:

https://simonbiggs.visualstudio.com/layer_linter/_build/results?buildId=5

**Comment by SimonBiggs** [comment]
Something weird happened with the macOS build. I'm happy to ignore that. I think this appears fixed :)

**Comment by seddonym** [comment]
Great! Maybe the mac build was just a network error, are you able to retrigger that build?

**Comment by SimonBiggs** [comment]
I did a rebuild, it rebuilt all of the matrix. This time that macOS did pass, but the other macOS didn't:

https://simonbiggs.visualstudio.com/layer_linter/_build/results?buildId=6

**Comment by SimonBiggs** [comment]
I've set it to rebuild one more time:

https://simonbiggs.visualstudio.com/layer_linter/_build/results?buildId=7

But I'm heading to bed now, so not sure how it'll go.

**Comment by seddonym** [comment]
I don't think it's anything to do with your code - I'm going to merge this to master. Thanks so much for your help on this!

**Comment by SimonBiggs** [comment]
You're welcome, my pleasure :) You mentioned a new build of layer-linter is coming. Will this be based on https://grimp.readthedocs.io/?

**Comment by seddonym** [comment]
Yes, exactly. The plan is to make it do everything Layer Linter does, but a more general purpose linter for a project's import graph - i.e. not just tied to thinking about things in terms of layers.

**Comment by SimonBiggs** [comment]
Very cool. :)

**Comment by SimonBiggs** [comment]
@seddonym might this be able to be forged into a release? :)

**Comment by seddonym** [comment]
Hi Simon,

Thanks for the nudge on this - I thought I'd already released it, but I hadn't!

This is now released. I've also added you as a contributor. Thanks again.

**Comment by SimonBiggs** [comment]
Thanks David :)

**Pull request merged**
